# Generated by Django 4.2.30 on 2026-04-30 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_type', models.CharField(choices=[('litre', 'Litre'), ('ml', 'Millilitre'), ('kg', 'Kilogram'), ('gram', 'Gram'), ('packet', 'Packet'), ('piece', 'Piece'), ('dozen', 'Dozen'), ('bundle', 'Bundle'), ('box', 'Box'), ('bottle', 'Bottle'), ('can', 'Can'), ('other', 'Other')], default='piece', max_length=30)),
                ('default_price_per_unit', models.DecimalField(decimal_places=2, help_text='Default/usual price per unit. Can be overridden per purchase.', max_digits=10)),
                ('category', models.CharField(blank=True, default='', help_text='Optional category, e.g., Dairy, Vegetables, Grains, Snacks.', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grocery_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Number of units bought (e.g., 2 litres, 0.5 kg).', max_digits=10)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Actual price paid per unit for this purchase.', max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, editable=False, help_text='Auto-calculated: quantity × price_per_unit.', max_digits=12)),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Exact date and time of purchase.')),
                ('notes', models.TextField(blank=True, default='', help_text="Optional notes, e.g., 'bought from local market'.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='tracker.groceryitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
    ]
